### ISSUE TITLE
Unable to build using clang-cl

### ISSUE THREAD

**Issue by Epixu** [madler/zlib#872]
Hi there, [I've been struggling with building](https://github.com/Epixu/zlib/actions/runs/6782142968/job/18433793954) zlib with MSVC's Clang-CL (`-A Win32 -T ClangCl` for example)
My speculation is, that the preprocessor gets confused somewhere, because under Clang-CL, both `_MSC_VER` and `__clang__` are defined, while only the latter has the problematic `include_next`. I'm unable to pinpoint the exact place of failure, though, as I'm not really familiar with zlib's configuration and source code

**Comment by Mr-Clam** [comment]
Can you use a different CMake generator such as Ninja?  We have a slightly different setup, but we are successfully compiling with an older version of clang-cl (version 10).  In our case, we're cross-compiling for Windows ARM using cmake + ninja on Linux.

`RC1021` looks like a resource compiler error.  Is it using the Microsoft resource compiler?  It can be pretty flakey and presumably wouldn't like the LLVM header where the error's occurring.  I can see in our build logs that that `zlib1.rc` is being processed with: `/opt/cmake-3.20.3-linux-x86_64/bin/cmake -E cmake_llvm_rc <root_path>/zlib/win32/zlib1.rc CMakeFiles/zlib.dir/win32/zlib1.res.pp /usr/bin/clang-cl-10 <...>`.  Maybe you can pass `-D CMAKE_VERBOSE_MAKEFILE=1` to the cmake config step to make your build log more informative?

**Comment by Mr-Clam** [comment]
> Any suggestions on how to circumvent the issue without switching to Ninja?

See how you get on [explicitly specifying](https://github.com/madler/zlib/issues/872#issuecomment-1799000496) the resource compiler.

> Would you consider having these test cases in your workflow?

I personally like to run tests where they exist because they sometimes catch problems (generally when I've misconfigured something!) and it saves time finding it this way, although I've never seen them fail for zlib.  We do do a `make test` for zlib on the platforms where we natively compile, but we have to skip this when cross-compiling.

**Comment by Epixu** [comment]
> Additionally, if it is using the wrong resource compiler, you can try to specify explicitly via the `RC` environmental variable before invoking the CMake configuration step, or by specifying `CMAKE_RC_COMPILER` in your CMakeLists.txt.

I followed your suggestion, specifying explicitly the path where llvm-rc.exe is located on the runner:
```yaml
         - name: Windows MSVC Win32 (clang-cl)
            os: windows-latest
            compiler: cl
            cmake-args: -A Win32 -T ClangCl -D CMAKE_RC_COMPILER="C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/Llvm/bin/llvm-rc.exe"
```
But it doesn't seem to reflect at all in the log, it continues to use `C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\x64\rc.exe` instead, as before

**Comment by Epixu** [comment]
Also, it is important to note, that I'm actually able to build zlib locally on my PC, the problem seems to be occuring only on the github runners for some reason

**Comment by Mr-Clam** [comment]
Sorry, I'm speculating: perhaps it's hardcoded behaviour for MCBuild with VS project files?  I can understand that you might not want to install ninja, but can you try the NMake generator instead, which comes with VS2022?

**Comment by Epixu** [comment]
I suppose Ninja has to be the solution, since locally Visual Studio seems to be using just that

**Comment by Mr-Clam** [comment]
I like Ninja: it's a single small binary, works the same way on all of our platforms and builds quickly.  But if this is a problem related to using VS project files, NMake might also work and doesn't require installing anything.  Just add `-G NMake Makefiles` to your cmake configure command.

**Comment by Epixu** [comment]
Now [I'm trying to configure using Ninja](https://github.com/Epixu/zlib/actions/runs/6788929828/job/18454989464), and it's just blatantly saying to me that `clang-cl.exe is not able to compile a simple test program`
I'm running `vcvarsXX.bat` and all

**Comment by Mr-Clam** [comment]
Does setting `CMAKE_C_COMPILER` fix this?  And possibly `CMAKE_CXX_COMPILER` (is there an C++ in zlib?) and `CMAKE_LINKER` (or is `CMAKE_C_LINK_EXECUTABLE`?).

**Comment by Epixu** [comment]
@Mr-Clam thank you very much for your time, I learned a great deal of stuff!
[I was able to finally configure Ninja on the Github runner](https://github.com/Epixu/zlib/actions/runs/6789283550/job/18456114957)

For any lurkers about, here's how I managed to do it:
```yaml
  - name: Windows MSVC Win32 (clang-cl)
    os: windows-latest
    compiler: clang-cl
    cmake-args: -G "Ninja" -DCMAKE_C_COMPILER=clang-cl -DCMAKE_C_FLAGS=-m32 -DCMAKE_MT="C:/Program Files (x86)/Windows Kits/10/bin/10.0.19041.0/x86/mt.exe"
    vcvars: cmd /c "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/Tools/VsDevCmd.bat" -arch=x86 &&
  - name: Windows MSVC Win64 (clang-cl)
    os: windows-latest
    compiler: clang-cl
    cmake-args: -G "Ninja" -DCMAKE_C_COMPILER=clang-cl -DCMAKE_C_FLAGS=-m64 -DCMAKE_MT="C:/Program Files (x86)/Windows Kits/10/bin/10.0.19041.0/x64/mt.exe"
    vcvars: cmd /c "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/Tools/VsDevCmd.bat" -arch=x64 &&
```
(here's the [full script](https://github.com/Epixu/zlib/blob/develop/.github/workflows/cmake.yml))

Conclusions:
1. Avoid the Visual Studio generators, if you have *.rc files - seems the resource compiler is hard-coded and can't be overridden.
2. You have to manually setup the environment in cmd, by calling `VsDevCmd.bat` with the appropriate arguments
3. CMAKE_MT must be manually specified when using Ninja, even after `VsDevCmd.bat`, as it is also for some reason hard-coded to not use the one provided with clang-cl - you have to manually point to the one coming from the windows SDK

I have absolutely no idea why this has to be so hard, and not fully automated at this point.
Do you have suggestions on where to file some issues? *cracks knuckles*
